### ISSUE TITLE
Future changes  -- With Scale System.

### ISSUE THREAD

**Issue by nonzzz** [fect-org/fect#215]
## Background

Util now, fect has been iterate for nearly a year, And our neighbor `geist` has already enterd the `Sclae` system.
It is undeniable that `scale` system is a good enough `ux` design solution. So, I want to add `scale` for `fect`.

## Plans

- May it will be a break change. But I will do my best to ensure incremental upgrades
- It will be implemented as soon as version `1.6` or `2.0`.
- We will use `attr` bind to avoid more damage.

**Comment by XeryYue** [comment]
## Update

If we decide add as a feature at `v1.6` , we don't enable this feature by default. And you can manually enable it，because I don't want to affect previous users.

- If in V1.6 

```js
<fe-theme-provide scale>
  <fe-button sclae={0.3} h="50px">
    Action
  </fe-button>
</fe-theme-provide>
```
you should use `theme-provide` component wrapper your application. And enable `sclae` prop .

- If in V2.0

Remove the existing size system. Use the sclae method directly

**Comment by nonzzz** [comment]
Just a discussion. If we break to ver `2.x`. should we need deployment two version of site? Or we only deployment the latest ?

**Comment by nonzzz** [comment]
I will close this issue. Unless i find a css solution. At present I don't have a good solution to the CSS problem. If implement the scale system,it is not ideal. ( This issue will reopen after i find a css solution.
